[package]
name = "day_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "1.1.2"
fancy-regex = "0.12.0"
regex = "1.10.2"
